reminder/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('reminders_app/', include('reminders_app.urls')),
    path('admin/', admin.site.urls),
]

reminders_app/urls.py
from django.urls import path

from . import views

app_name = 'reminders_app'

urlpatterns = [
	# /reminders_app
	path('', views.IndexView.as_view(), name='index'),
	# /reminders_app/7/
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	# /reminders_app/add/
	path('add/', views.add, name='add'),
	# /reminders_app/insert/
	path('insert/', views.insert, name='insert'),
]

reminders_app/models.py
from django.db import models

import datetime

# Create your models here.
class Reminder(models.Model):
	title = models.CharField(max_length=500)
	date = models.DateField()
	time = models.TimeField()
	note = models.TextField()

	def are_time_date_valid(self):
		current_date = datetime.date.today()
		current_time = datetime.datetime.now().time()

		if (self.date < current_date or (self.date == current_date and self.time < current_time)):
			return False
		return True

	def __str__(self):
		return self.title

reminders_app/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
import datetime
#from django.template import loader

from .models import Reminder

class IndexView(generic.ListView):
	template_name = 'reminders_app/index.html'
	context_object_name = 'latest_reminder_list'

	def get_queryset(self):
		""" Return the last five reminders. """
		return Reminder.objects.order_by("-date")[:5]

class DetailView(generic.DetailView):
	model = Reminder
	template_name = 'reminders_app/detail.html'
		
def detail(request, reminder_id):
	reminder = get_object_or_404(Reminder, pk=reminder_id)
	return render(request, 'reminders_app/detail.html', {'reminder': reminder})

def add(request):
	return render(request, 'reminders_app/add.html')

def insert(request):
	data_dict = request.POST
	print (data_dict)
	date = datetime.datetime.strptime(data_dict['date'], "%Y-%m-%d").date()
	time = datetime.datetime.strptime(data_dict['time'], "%H:%M").time()
	try:
		reminder = Reminder(title=data_dict['title'], date=date, time=time, note=data_dict['note'])
	except (KeyError, Reminder.DoesNotExist):
		return render(request, 'reminders_app/add.html', {'error_message': "You haven't filled in all the fields."})
	else:
		if reminder.are_time_date_valid():
			reminder.save()
			return HttpResponseRedirect(reverse('reminders_app:detail', args=(reminder.id,)))
		else:
			return render(request, 'reminders_app/add.html', {'error_message': "Can't remind you for an event in the past!"})

reminders_app/templates/reminders_app/add.html
<h2>Add Reminder</h2>
{% if error_message %}<p style="color: red"><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'reminders_app:insert' %}" method="post">
	{% csrf_token %}
	<label for="title">Title</label>
	<input type="text" name="title" required><br><br>
	<input type="date" name="date" required>
	<input type="time" name="time" required><br><br>
	<label for="note">Note</label>
	<textarea name="note"></textarea><br><br>
	<input type="submit" value="Add">
</form>

reminders_app/templates/reminders_app/detail.html
<h3>{{reminder.title}}</h3>
<hr>
<body>
	<div>
		<div>
			<span style="display:inline-block; width: 200px; color:grey;">{{reminder.date}}</span>
			<span style="display:inline-block; width: 200px; color:grey;">{{reminder.time}}</span>
		</div>
		<div>
			{{reminder.note}}
		</div>
	</div>
</body>

reminders_app/templates/reminders_app/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'reminders_app/style.css' %}">

<h2>Reminders</h2>
{% if latest_reminder_list %}
	<ul>
		{% for reminder in latest_reminder_list %}
			<li><a href="{% url 'reminders_app:detail' reminder.id %}">{{reminder.title}}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No reminders!</p>
{% endif %}
<button onclick="location.href='{% url "reminders_app:add" %}'">Add Reminder</button>